/**
 * Mock node executor — Block 3 test-author deliverable.
 *
 * A drop-in replacement for the real SDK node runner. It never calls the
 * Anthropic SDK and never costs tokens. Per-node scenarios are configured
 * via a ScenarioMap passed at construction time.
 *
 * Design contract (engine author note):
 *   The engine calls `executor(nodeId, node, ctx)` and handles the returned
 *   NodeExecResult. To swap in the real SDK runner, replace the NodeExecutor
 *   function reference — no engine logic changes required.
 *
 * Scenarios:
 *   'success'          — writes declared `produces` files, returns done
 *   'missing-produces' — returns done WITHOUT writing produces files
 *                        (engine's produces-contract check then marks failed)
 *   'reviewer-fail'    — returns failed / retryable:false
 *                        (engine checks optional:true → skipped)
 *   'gate-reject'      — returns awaiting-gate with canned rejection reason
 *   'loop-exhaust'     — returns failed with a loop-exhausted message
 *   'transient-error'  — returns failed / retryable:true (engine may retry)
 *
 * DECISIONS.md entry:
 *   block3 · NodeExecResult / ExecutionCtx / NodeExecutor types defined in
 *   mock-executor.ts (types.ts is off-limits per hard rules); engine author
 *   may relocate them to a shared types module in Block 4.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Node } from "./types.js";

// ---------------------------------------------------------------------------
// Public types (engine author: swap NodeExecutor to go live)
// ---------------------------------------------------------------------------

export type NodeExecResult =
  | { status: "done"; artifacts: string[]; cost: number; sessionId: string }
  | { status: "failed"; error: string; retryable: boolean }
  | {
      status: "awaiting-gate";
      iteration: number;
      sessionId: string;
      artifactPath: string;
    };

export type ExecutionCtx = {
  /** Root run directory: ~/.local/share/dagrunner/runs/<run-id>/ */
  runDir: string;
  /** Per-node artifact directory: runDir/<nodeId>/ */
  artifactsDir: string;
  /** Absolute path to the checked-out worktree for this run. */
  worktreePath: string;
  /** Optional: existing Claude session ID for gate resume. */
  sessionId?: string;
};

/** The interface the engine calls; real SDK runner has the same signature. */
export type NodeExecutor = (
  nodeId: string,
  node: Node,
  ctx: ExecutionCtx,
) => Promise<NodeExecResult>;

// ---------------------------------------------------------------------------
// Scenario type
// ---------------------------------------------------------------------------

export type NodeScenario =
  | "success"
  | "missing-produces"
  | "reviewer-fail"
  | "gate-reject"
  | "loop-exhaust"
  | "transient-error";

/** Map from node id → scenario. Nodes absent from the map default to 'success'. */
export type ScenarioMap = Record<string, NodeScenario>;

// ---------------------------------------------------------------------------
// Canned values
// ---------------------------------------------------------------------------

const MOCK_SESSION_ID = "mock-session-abc123";
const MOCK_COST = 0.0001;
const MOCK_GATE_ARTIFACT = "awaiting-review.md";

// ---------------------------------------------------------------------------
// Factory — returns a NodeExecutor bound to the given scenario map
// ---------------------------------------------------------------------------

/**
 * Create a mock NodeExecutor that uses `scenarios` to choose per-node
 * behaviour. Unrecognised node ids default to 'success'.
 */
export function createMockExecutor(scenarios: ScenarioMap = {}): NodeExecutor {
  return async function mockExecutor(
    nodeId: string,
    node: Node,
    ctx: ExecutionCtx,
  ): Promise<NodeExecResult> {
    const scenario: NodeScenario = scenarios[nodeId] ?? "success";

    // Ensure the artifacts directory exists for scenarios that write files.
    if (scenario === "success" || scenario === "gate-reject") {
      mkdirSync(ctx.artifactsDir, { recursive: true });
    }

    switch (scenario) {
      case "success": {
        // Write each declared produces file with canned content.
        const artifacts: string[] = [];
        if (node.produces !== undefined) {
          for (const filename of node.produces) {
            const fullPath = join(ctx.artifactsDir, filename);
            writeFileSync(
              fullPath,
              `# Mock artifact: ${filename}\nGenerated by mock executor for node "${nodeId}".\n`,
              "utf8",
            );
            artifacts.push(fullPath);
          }
        }
        return {
          status: "done",
          artifacts,
          cost: MOCK_COST,
          sessionId: ctx.sessionId ?? MOCK_SESSION_ID,
        };
      }

      case "missing-produces": {
        // Return 'done' but deliberately skip writing produces files.
        // The ENGINE's produces-contract check (Theme 4) will detect the
        // absence of declared files and mark the node failed.
        return {
          status: "done",
          artifacts: [],
          cost: MOCK_COST,
          sessionId: ctx.sessionId ?? MOCK_SESSION_ID,
        };
      }

      case "reviewer-fail": {
        return {
          status: "failed",
          error: `Mock reviewer failure for node "${nodeId}"`,
          retryable: false,
        };
      }

      case "gate-reject": {
        // Write a canned feedback artifact (the real runner writes feedback-N.md).
        const artifactPath = join(ctx.artifactsDir, MOCK_GATE_ARTIFACT);
        writeFileSync(
          artifactPath,
          `# Review feedback\nMock gate rejection for node "${nodeId}".\nAdd error handling section.\n`,
          "utf8",
        );
        return {
          status: "awaiting-gate",
          iteration: 1,
          sessionId: ctx.sessionId ?? MOCK_SESSION_ID,
          artifactPath,
        };
      }

      case "loop-exhaust": {
        return {
          status: "failed",
          error: `Loop exhausted for node "${nodeId}" — maxIterations reached`,
          retryable: false,
        };
      }

      case "transient-error": {
        return {
          status: "failed",
          error: `Transient infra error for node "${nodeId}" (529 / timeout)`,
          retryable: true,
        };
      }
    }
  };
}

// ---------------------------------------------------------------------------
// Self-contained smoke tests for the mock executor itself
// (these run via node --test and pass with no engine present)
// ---------------------------------------------------------------------------

import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";

const MOCK_NODE: Node = {
  id: "test-node",
  command: "/test",
  produces: ["output.md"],
};

const MOCK_CTX = (): ExecutionCtx => {
  const runDir = mkdtempSync(join(tmpdir(), "dagrunner-mock-"));
  return {
    runDir,
    artifactsDir: join(runDir, "test-node"),
    worktreePath: "/tmp/mock-worktree",
  };
};

test("mock executor — success writes produces files", async () => {
  const executor = createMockExecutor({ "test-node": "success" });
  const ctx = MOCK_CTX();
  const result = await executor("test-node", MOCK_NODE, ctx);

  assert.equal(result.status, "done");
  if (result.status === "done") {
    assert.equal(result.artifacts.length, 1);
    assert.ok(existsSync(result.artifacts[0] ?? ""));
  }
});

test("mock executor — missing-produces returns done but writes no files", async () => {
  const executor = createMockExecutor({ "test-node": "missing-produces" });
  const ctx = MOCK_CTX();
  const result = await executor("test-node", MOCK_NODE, ctx);

  assert.equal(result.status, "done");
  if (result.status === "done") {
    assert.equal(result.artifacts.length, 0);
    // The produces file must be absent — this is what the engine detects.
    const expected = join(ctx.artifactsDir, "output.md");
    assert.ok(
      !existsSync(expected),
      "produces file must NOT exist for engine to catch",
    );
  }
});

test("mock executor — transient-error returns retryable:true", async () => {
  const executor = createMockExecutor({ "test-node": "transient-error" });
  const ctx = MOCK_CTX();
  const result = await executor("test-node", MOCK_NODE, ctx);

  assert.equal(result.status, "failed");
  if (result.status === "failed") {
    assert.equal(result.retryable, true);
  }
});

test("mock executor — gate-reject returns awaiting-gate with artifact path", async () => {
  const executor = createMockExecutor({ "test-node": "gate-reject" });
  const ctx = MOCK_CTX();
  const result = await executor("test-node", MOCK_NODE, ctx);

  assert.equal(result.status, "awaiting-gate");
  if (result.status === "awaiting-gate") {
    assert.ok(
      existsSync(result.artifactPath),
      "gate artifact must exist on disk",
    );
    assert.equal(result.iteration, 1);
  }
});
